use crate::engine::{directions::squares::*, piece::*};

pub const STARTING_CONFIG: &[(Piece, Square)] = &[
    (WHITE_KING, E1),
    (WHITE_QUEEN, D1),
    (WHITE_ROOK, A1),
    (WHITE_ROOK, H1),
    (WHITE_BISHOP, C1),
    (WHITE_BISHOP, F1),
    (WHITE_KNIGHT, B1),
    (WHITE_KNIGHT, G1),
    (WHITE_PAWN, A2),
    (WHITE_PAWN, B2),
    (WHITE_PAWN, C2),
    (WHITE_PAWN, D2),
    (WHITE_PAWN, E2),
    (WHITE_PAWN, F2),
    (WHITE_PAWN, G2),
    (WHITE_PAWN, H2),
    (BLACK_KING, E8),
    (BLACK_QUEEN, D8),
    (BLACK_ROOK, A8),
    (BLACK_ROOK, H8),
    (BLACK_BISHOP, C8),
    (BLACK_BISHOP, F8),
    (BLACK_KNIGHT, B8),
    (BLACK_KNIGHT, G8),
    (BLACK_PAWN, A7),
    (BLACK_PAWN, B7),
    (BLACK_PAWN, C7),
    (BLACK_PAWN, D7),
    (BLACK_PAWN, E7),
    (BLACK_PAWN, F7),
    (BLACK_PAWN, G7),
    (BLACK_PAWN, H7),
];
